name: Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'source/_posts/**/*.md'
  workflow_run:
    workflows: ["Translate Posts"]
    types: [completed]

jobs:
  verify:
    # Run on push (non-post changes) OR after translation workflow succeeded on main
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # When triggered by workflow_run, ensure we build latest main
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install verifier deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Verify all posts translated
        run: |
          python .github/workflows/verify_translations.py

  pages:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      # Hexo ----------------------
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
