name: Translate Posts

on:
  push:
    branches: [ main ]
    paths:
      - 'source/_posts/**/*.md'
  workflow_dispatch: {}
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write

concurrency:
  group: translate-${{ github.ref }}
  cancel-in-progress: false

jobs:
  translate:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    environment: PROD
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
      OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install 'openai>=1.37,<2' pyyaml

      - name: List changed files
        id: diff
        shell: bash
        run: |
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            git diff --name-only HEAD~1 HEAD > changed_raw.txt || true
          else
            git diff --name-only "$BEFORE" "$AFTER" > changed_raw.txt || true
          fi
          grep -E '^source/_posts/.*\.md$' changed_raw.txt > changed.txt || true
          echo "Changed files:"
          cat changed.txt || true

      - name: Run translator (changed only)
        run: |
          python .github/workflows/translate_posts.py \
            --src-root source/_posts \
            --default-lang en \
            --other-lang zh-TW \
            --changed-file-list changed.txt \
            --model "${OPENAI_MODEL:-gpt-5-mini-2025-08-07}"

      - name: Commit and push if changed
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(i18n): auto-translate posts"
            git push
          else
            echo "No changes to commit."
          fi

  backfill:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    environment: PROD
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
      OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install 'openai>=1.37,<2' pyyaml

      - name: Run translator (backfill all)
        run: |
          python .github/workflows/translate_posts.py \
            --src-root source/_posts \
            --default-lang en \
            --other-lang zh-TW \
            --scan-all \
            --model "${OPENAI_MODEL:-gpt-5-mini-2025-08-07}"

      - name: Commit and push if changed
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(i18n): backfill translations"
            git push
          else
            echo "No changes to commit."
          fi
